export declare const rendererTraceCategory = "ns-renderer";
export declare const routerTraceCategory = "ns-router";
export declare const listViewTraceCategory = "ns-list-view";
export declare function rendererLog(msg: any): void;
export declare function rendererError(message: string): void;
export declare function routerLog(message: string): void;
export declare function styleError(message: string): void;
export declare function listViewLog(message: string): void;
export declare function listViewError(message: string): void;
